spring:
  application:
    name: workhub-saas
  datasource:
    url: jdbc:postgresql://localhost:5432/workhub
    username: postgres
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
