spring:
  application:
    name: workhub-saas
  datasource:
    url: jdbc:postgresql://localhost:5432/workhub
    username: postgres
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
