apiVersion: v1
kind: ConfigMap
metadata:
  name: workhub-config
  namespace: workhub
data:
  SPRING_DATASOURCE_URL: "jdbc:postgresql://postgres-service:5432/workhub"
  SPRING_DATASOURCE_USERNAME: "postgres"
  SPRING_RABBITMQ_HOST: "rabbitmq-service"
  SPRING_RABBITMQ_PORT: "5672"
  SPRING_RABBITMQ_USERNAME: "guest"
  OTEL_EXPORTER_OTLP_ENDPOINT: "http://jaeger-service:4318/v1/traces"
