apiVersion: v1
kind: ConfigMap
metadata:
  name: workhub-config
data:
  SPRING_PROFILES_ACTIVE: "prod"
  SPRING_DATASOURCE_URL: "jdbc:postgresql://workhub-db:5432/workhub"
  SPRING_RABBITMQ_HOST: "workhub-rabbitmq"
  SPRING_RABBITMQ_PORT: "5672"
