apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq-deployment
  namespace: workhub
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
      - name: rabbitmq
        image: rabbitmq:3-management
        ports:
        - containerPort: 5672
        - containerPort: 15672
        env:
        - name: RABBITMQ_DEFAULT_USER
          value: "guest"
        - name: RABBITMQ_DEFAULT_PASS
          valueFrom:
            secretKeyRef:
              name: workhub-secrets
              key: SPRING_RABBITMQ_PASSWORD
        livenessProbe:
          exec:
            command: ["rabbitmq-diagnostics", "check_running"]
          initialDelaySeconds: 60
          periodSeconds: 15
          failureThreshold: 3
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-service
  namespace: workhub
spec:
  selector:
    app: rabbitmq
  ports:
    - name: amqp
      protocol: TCP
      port: 5672
      targetPort: 5672
    - name: management
      protocol: TCP
      port: 15672
      targetPort: 15672
