apiVersion: v1
kind: Secret
metadata:
  name: workhub-secret
type: Opaque
data:
  SPRING_DATASOURCE_USERNAME: cG9zdGdyZXM=
  SPRING_DATASOURCE_PASSWORD: cGFzc3dvcmQ=
  SPRING_RABBITMQ_USERNAME: Z3Vlc3Q=
  SPRING_RABBITMQ_PASSWORD: Z3Vlc3Q=
  WORKHUB_JWT_SECRET: NDA0RTYzNTI2NjU1NkE1ODZFMzI3MjM1NzUzODc4MkY0MTNGNDQyODQ3MkI0QjYyNTA2NDUzNjc1NjZCNTk3MA==
