apiVersion: v1
kind: Secret
metadata:
  name: workhub-secrets
  namespace: workhub
type: Opaque
data:
  SPRING_DATASOURCE_PASSWORD: "cGFzc3dvcmQ=" # password
  SPRING_RABBITMQ_PASSWORD: "Z3Vlc3Q="    # guest
  WORKHUB_JWT_SECRET: "NDA0RTYzNTI2NjU1NkE1ODZFMzI3MjM1NzUzODc4MkY0MTNGNDQyODQ3MkI0QjYyNTA2NDUzNjc1NjZCNTk3MA=="
